language: python
python:
    - "3.6"

before_install:
    - pip install pep8
    - pep8 $TRAVIS_BUILD_DIR/vctl/*/*.py --ignore E501

install:
    - pip install -e file://$TRAVIS_BUILD_DIR

script:
    nosetests
