language: python
python:
    - "3.6"

before_install:
    - pip install pep8
    - pep8 $TRAVIS_BUILD_DIR/vctl/*/*.py --ignore E501,E121,E123,E126,E226,E24,E704

install:
    - pip install -e file://$TRAVIS_BUILD_DIR

script:
    vctl --help
    nosetests
