language: python
python:
    - "3.4"
    - "3.6"

before_install:
    - pip install pep8
    - pep8 $TRAVIS_BUILD_DIR/vctl/helpers/*.py
    - pep8 $TRAVIS_BUILD_DIR/vctl/config/*.py
    - pep8 $TRAVIS_BUILD_DIR/vctl/get/*.py

install:
    - pip install -e file://$TRAVIS_BUILD_DIR

script:
    nosetests
