contexts:
- context:
    cookie: vmware_soap_session=1e336dc3-53f6-43b9-95bf-baf1efb5da45
    username: user
    vcenter: 127.0.0.1
  name: 127.0.0.1-tmcsf
- context:
    cookie: vmware_soap_session=3b65293a-8678-47bf-9684-7f5da0fc24c1
    username: user
    vcenter: 127.0.0.1
  name: 127.0.0.1-llphj
- context:
    token: vmware_soap_session=a76d248c-2d26-44cc-91c3-92512296c100
    username: user
    vcenter: 127.0.0.1
  name: 127.0.0.1-hpgce
current-context: 127.0.0.1-hpgce
